const languages = {
  english: {
      w1 : "Shop with India's Agri Products online store",
      w2 : 'It is now very easy to reach the best quantity among all the products go',
      nx : 'Next',
      wht : "What's your mobile number?",
      mob : 'Mobile Number',
      mt : 'You will receive a verification code shortly.',
      sn : 'Send OTP',
      cn : 'Continue as Guest',
      sn2 : 'Enter 5 - Digit code send at',
      rc : "Didn't Receive Code?",
      ro : 'Resend OTP',
      vo : 'Verify OTP',
      sd : 'Enter Your Shop Details',
      sd2 : 'Please enter your shop name, Address, GST, PAN no. etc.',
      sp : 'Shop Name',
      rq : 'Required',
      ep : 'Enter PAN No.',
      eg : 'Enter GST No. (Optional)',
      um : 'Upload MSME',
      yes : 'Yes',
      no : 'No',
      up : 'Upload',
      agree : 'I agree to the above mentioned declaration',
      pr : 'Proceed',
      i : 'I',
      dec : 'hereby affirm that currently we are NOT REGISTERED ENTERPRISES under MSME Act. I further assure that, if in future, we get registered under MSME Act, we will inform you immediately.',
      up2 : 'Uploaded',
      pro : 'Proceed',
      so : 'Select Option',
      cam : 'Camera',
      gal : 'Gallery',
      can : 'Cancel',
      sr : 'Search..',
      spc : 'Shop By Category',
      top : 'Top Selling Products',
      micro : 'Micro Nutrients',
      short : 'Gramik Shorts',
      spb : 'Shop By Brands',
      kheti : 'Kheti Ki Jaankari',
      all : 'View All',
      see : 'See More',
      mc : 'My Cart',
      ec : 'Your cart is empty !',
      ec2 : 'Add products to your cart to place order',
      ssp : 'Start Shopping',
      wish : 'Wishlist',
      wish2 : 'Your Wishlist is empty !',
      wish3 : 'Add products to your wishlist to place order',
      to : 'Track Orders',
      all2 : 'All',
      pen : 'Pending',
      del : 'Delivered',
      can2 : 'Cancelled',
      nor : 'No Orders Found !',
      py : 'Payment',
      pym : 'Payment Method',
      pym2 : 'Choose your payment method',
      bal : 'Balance',
      inst : 'Installment',
      comp : 'Complete Payment',
      payn : 'Pay Now',
      noti : 'Notifications',
      noti2 : 'No notifications yet !',
      epr : 'Edit Profile',
      ma : 'My Address',
      mo : 'My Orders',
      si : 'Shop Info',
      mw : 'My Wishlist',
      cu : 'Chat with us',
      ts : 'Talk to our support',
      pp : 'Privacy Policy',
      mu : 'Mail to us',
      da : 'Delete Account',
      lg : 'Logout',
      lg2 : 'Sure to logout?',
      lg3 : 'Are you sure you want to logout of gramik?',
      pd : 'Product Details',
      prc : 'Price',
      sz : 'Size',
      sv : 'Select Variant',
      po : 'Product Overview',
      bs : 'Best Selling',
      cr : 'Customer Reviews',
      st : 'star',
      rp : 'Review this product',
      rp2 : 'Share your thoughts with other customers',
      wpr : 'Write Product Review',
      ac : 'Add to Cart',
      by : 'Buy Now',
      rpr : 'Rate Product',
      tyr : 'Type your review...',
      smp : 'Similar Products',
      vf : 'Verified Farmer',
      ph : 'people found this helpful',
      hp : 'Helpful?',
      sf : 'Select Farmer',
      sb : 'Submit',
      wl : 'Welcome!',
      nm : 'Name',
      em : 'Email',
      phn : 'Phone No.',
      pin : 'Pin Code',
      sa : 'Shop Address',
      vl : 'Village / Town',
      ds : 'District',
      opt : 'Optional',
      upc : 'Upload Firm / Shop PAN Card',
      usl : 'Upload Seed License',
      upl : 'Upload Pesticide License',
      ufl : 'Upload Fertilizer License',
      usp : 'Upload Shop Photo',
      eg2 : 'Upload GST No.',
      rmp : 'Remove product from cart!',
      rmp2 : 'Are you sre to remove this product from cart?',
      yr : 'Yes, Remove',
      bd : 'Bill Details',
      sub : 'Sub Total',
      tax : 'Tax',
      shp : 'Shipping Charges',
      tp : 'Total Payable',
      ptc : 'Proceed to Checkout',
      cd : 'Coupon Discount',
      acc : 'Apply Coupon Code',
      sc : 'Select Coupon',
      ca : 'Coupon Applied',
      rmv : 'Remove',
      sdt : 'Shipping Details',
      cda : 'Choose Delivery address',
      sha : 'Shipping Address',
      sho : 'Shipping Options',
      db : 'Delivery By',
      ptp : 'Proceed to Payment',
      sad : 'Select Address',
      upa : 'Update Address',
      sadd : 'Select Address',
      edd : 'Edit Address',
      add2 : 'Add Address',
      fa : 'Full Address',
      lnd : 'Landmark',
      spa : 'Save as primary address',
      dela : 'Delete Address',
      dela2 : 'Are you sure you want to delete this shipping address?',
      yd : 'Yes, Delete',
      addr : 'Address',
      nad : 'No Address Found !',
      nad2 : 'Add address to place order',
      adn : 'Add Now',
      payd : 'Payment Details',
      plo : 'Place Order',
      paym : 'Select Payment Method',
      done : 'Done!',
      done2 : 'Your order has been successfully placed !!',
      fail : "We couldn't proceed your payment!",
      fail2 : 'Please, change your payment method or try again',
      try : 'Try Again',
      ch : 'Change',
      plo2 : 'Placed on',
      itm : 'Items',
      due : 'Due In',
      od : 'Order Details',
      por : 'Products Ordered',
      qy : 'Quantity',
      oid : 'Order ID',
      tm : 'Total Amount',
      opl : 'Order Placed',
      ocn : 'Order Confirmed',
      osp : 'Order Shipped',
      ofd : 'Out for Delivery',
      odl : 'Order Delivered',
      noa : 'Not Available',
      csp : 'Contact Support',
      cano : 'Cancel Order',
      pya : 'Paid Amount',
      pna : 'Pending Amount',
      reo : 'Reorder Item',
      doi : 'Download Quotation/Invoice',
      rnr : 'Rating & Review',
      rnr2 : 'Share your thoughts with other customers',
      rnr3 : 'You rated this order',
      tex : 'Tell us about your experience..',
      cls : 'Close',
      canr : 'Please provide a reason for cancellation !!',
      slr : 'Select Reason',
      do2 : 'Are you sure you want to delete your gramik account?',
      sbc : 'Search By Category',
      sbb : 'Search by Brand',
      prd : 'Products',
      sry : "Sorry, we couldn't find any matching result for your search.",
      exc : 'Explore Categories',
      res : 'Recent Search',
      cla : 'Clear All',
      exb : 'Explore Brands',
      npf : 'No Products found !',
      npf2 : 'Explore prodcuts in other category or brands',
      sfl : 'Select Filter',
      sfl2 : 'Sort or filter the products',
      ct2 : 'Categories',
      brd : 'Brands',
      clr : 'Clear',
      flt : 'Filter',
      flp : 'Filtered Products',
      su : 'Select Unit',
      add : 'Add',
      vcrt : 'View Cart',
      wyn : "What's your name?",
      ename : 'Enter Name',
      cnt : 'Continue',
      recv : 'Recently Viewed',
      out : 'out of 5',
      things : 'Things To Know',
      sow : 'Sowing Time',
      har : 'Harvesting',
      review : 'Reviews',
      area : 'Area of Sowing',
      coup : 'Coupon',
      ecode : 'Enter Code',
      acc2 : 'Apply Coupon',
      apply : 'Apply',
      ssa : 'Select Shipping Address',
      grw : 'Gramik Wallet',
      hom : 'Home',
      shop : 'Shop',
      ord3 : 'Orders',
      acct : 'Account',
      afd : 'Add Farmer Details',
      laa : 'Land Area (Acre)',
      csa : 'Crop Sown Annually',
      csc : 'Currently Sown Crop',
      catt : 'Do you have any cattle?',
      kisan : 'Do you have Kisan Credit Card?',
      tractor : 'Do you have Tractor?',
      adhaar : 'Upload Your Aadhar Card',
      upan : 'Upload Your PAN Card',
      crf : 'Do you want to avail credit facility?',
      save : 'Save',
      nny : 'No Notifications Yet !',
      nny2 : 'Add products to your cart to place order',
      lang : 'Language',
      lang2 : 'Select your language',
      avb : 'Available Balance',
      addm : 'Add Money',
      ltr : 'Last Transactions',
      notr : 'Not Transactions Yet !',
      wtp : 'Wallet Topup !',
      wtp2 : 'Topup your wallet for easy order payments',
      ena : 'Enter Amount',
      topw : 'Topup Wallet',
      hello : 'Hello',
      tos : "Today's Sales",
      tots : 'Total Sales',
      ya : 'You Achieved',
      tmt : 'This Month Target',
      lms : 'Last Month Sales',
      lmt : 'Last Month Target',
      toto : 'Total Orders',
      peno : 'Pending Orders',
      delo : 'Delivered Orders',
      backl : 'Backlogs',
      cru : 'Credit Utilized',
      yfar : 'Your Farmers',
      totf : 'Total Farmers',
      recently : 'Recently',
      recently2 : 'Farmers added this month',
      recently3 : 'Cordinator’s added this month',
      blc : "Block Co-Ordinator's",
      totc : "Total Co-Ordinator’s",
      peerp : 'Peer Partners',
      totp : "Total Peer Partners",
      myfar : 'My Farmers',
      creditf : 'Credit Facility',
      tcr : 'Total Credit',
      pena : 'Pending Amount',
      tots2 : 'Total Spending',
      repay : 'Repayments',
      stm : 'Spent this month',
      month : 'Monthly',
      week : 'Weekly',
      year : 'Yearly',
      allt : 'All Time',
      spi : 'Spent in',
      cred : 'Credits',
      selc : 'Select Crops',
      selt : 'Selected',
      post : 'Post Office',
      rmf : 'Delete Farmer?',
      rmf2 : 'Are you sure you want to delete this farmer?',
      update : 'Update Available',
      update2 : 'Please update Gramik App to access all features',
      updaten : 'Update',
      guest : 'Countinue as guest',
      cmeet : 'Create Farmer Meeting',
      cmeet2 : 'Enter Farmer Meeting Details',
      date : 'Select Date',
      fmeet : 'Farmer Meetings',
      tdy : 'Today',
      tmr : 'Tomorrow',
      week : 'Entire Week',
      nmeet : 'No Meetings found!',
      addf : 'Add Farmers',
      mphoto : 'Meeting Photos',
      mphoto2 : 'Add Photos',
      trt : 'Before Treatment Images',
      trt2 : 'After Treatment Images',
      ntr : 'No Product Trials Found!',
      ctr : 'Create Product Trial',
      prt : 'Product Trails',
      sela : 'Select Agenda',
      selm : 'Select Meeting Type',
      selc2 : 'Select Associate Center',
      selc3 : 'Select Farmer Crops',
      locd : 'Location Details',
      ens : 'Enter State',
      end : 'Enter District',
      enb : 'Enter Block',
      env : 'Enter Village',
      frn : 'Farmer Name',
      totl : 'Total Land (Acre)',
      trtl : 'Treated Land (Acre)',
      dos : 'Date of Sowing',
      selcr : 'Select Crop',
      selpr : 'Select Product',
      bti : 'Before Treatment Images',
      lgn : 'Gramik Login',
      lgn2 : 'Login to gramik app to access all features',
      lgn3 : 'Login Now',
      srt : 'Select Retailers',
      ard : 'Add Retailer Details',
      addq : 'Add Quantity',
      nr : 'No Retailers Found!',
      nr2 : 'Add Retailers to place order',
      crd : 'Create Demand',
      dsn : 'District Name',
      bln : 'Block Name',
      agn : 'Agent Name',
      retn : 'Retailer Name',
      retmn : 'Retailer Mobile Number',
      comc : 'Coming Crop',
      brn : 'Brand Name',
      prn : 'Product Name',
      vrt : 'Variant',
      expr : 'Expected Rate',
      selb : 'Select Brand',
      qy2 : 'Quantity (pieces)',
      upp : 'Update Payment Status',
      scr : 'Attach NEFT / RTGS Screenshot',
      tnx : 'Transaction ID (Optional)',
      trm : 'Training Material',
      train : 'Training',
      leaf : 'Leaflets',
      ndoc : 'No documents found !',
      doc : 'Document',
      mret : 'My Retailers',
      ref : 'App Referral',
      eg3 : 'GST Number',
      usl2 : 'Seed License Number',
      upl2 : 'Pesticide License Number',
      ufl2 : 'Fertilizer License Number',
      qoute : 'Quoted Rate',
      refc : 'Referral Code',
      nref : 'No app referrals found !',
      nref2 : 'Refer and share Gramik Retailer App',
      nref3 : 'Share App Link',
      ats : 'Attach Screenshot',
      tra : 'Transfer Amount',
      tdp : 'Today Purchase',
      prc2 : 'Price',
      sz2 : 'Pack Size',
      dml : 'Demand List',
      cnm : 'Confirmed',
      nod : 'No Demands Found !',
      khata : 'Khata Book',

      gmka : 'Dr Kranti',
avcoins : 'Available Coins',
upcc : 'Upload Crop or Cattle Image',
chs : 'Choose source',
tlkx : 'Talk to our experts',
nmf : 'No History Yet !',
nmf2 : 'Dr. Kranti AI is here to assist you with any agriculture or cattle related problems.',
hold : 'Hold On for 1-2 mins! Dr Kranti is analyzing...',
tyq : 'Type your question...',
ingc : 'Insufficient Gramik Coins',
 grcom : 'Gramik Community',
      like : 'Like',
      comments : 'Comments',
      upos : 'Update ',
      retd : 'Retailer Details',
      seld : 'Select Distributor'




  },
  hindi: {
     w1 : "भारत के सर्वोत्तम कृषि उत्पाद  ग्रामिक के  ऑनलाइन स्टोर से खरीदें",
     w2 : 'सभी कृषि उत्पाद आपके घर तक पहुचना हुआ आसान ',
     nx : 'आगे बढ़ें',
     wht : "आपका मोबाइल नंबर क्या है ?",
     mob : 'मोबाइल नंबर',
     mt : 'आपको शीघ्र ही एक ओटीपी प्राप्त होगा',
     sn : 'ओटीपी भेजें',
     cn : 'अतिथि के रूप में जारी रखें',
     sn2 : 'कृपया ५ अंको का ओटीपी कोड दर्ज करें',
     rc : 'कोड प्राप्त नहीं हुआ?',
     ro : 'ओटीपी दोबारा भेजें',
     vo : 'सत्यापित करें',
     sd : 'अपनी दुकान का विवरण दर्ज करें',
     sd2 : 'कृपया अपनी दुकान का नाम, पता, जीएसटी, पैन नंबर दर्ज करें।',
     sp : 'दुकान का नाम',
     rq : 'आवश्यक',
     ep : 'पैन नंबर दर्ज करें.',
     eg : 'जीएसटी नंबर दर्ज करें (वैकल्पिक)',
     um : 'एमएसएमई अपलोड करें',
     yes : 'हाँ',
     no : 'नहीं',
     up : 'अपलोड',
     agree : 'मैं उपर्युक्त घोषणा से सहमत हूं',
     pr : 'आगे बढ़ना',
     i : 'मैं',
     dec : 'इसके द्वारा पुष्टि की जाती है कि वर्तमान में हम एमएसएमई अधिनियम के तहत पंजीकृत उद्यम नहीं हैं। मैं यह भी आश्वासन देता हूं कि, यदि भविष्य में, हम एमएसएमई अधिनियम के तहत पंजीकृत होंगे, तो हम आपको तुरंत सूचित करेंगे।',
     up2 : 'अपलोड किए गए',
     pro : 'आगे बढ़ना',
     so : 'विकल्प चुनें',
     cam : 'कैमरा',
     gal : 'गैलरी',
     can : 'रद्द करें',
     sr : 'खोजें',
     spc : 'केटेगरी के अनुसार खरीदारी',
     top : 'सबसे ज्यादा बिकने वाले उत्पाद',
     micro : 'माइक्रो न्यूट्रिएंट',
     short : 'ग्रामिक शॉर्ट्स',
     spb : 'ब्रांड्स द्वारा खरीदारी करें',
     kheti : 'खेती की जानकारी',
     all : 'सभी देखें',
     see : 'और देखें',
     mc : 'मेरा कार्ट',
     ec : 'आपका कार्ट खाली है !',
     ec2 : 'ऑर्डर देने के लिए अपने कार्ट में उत्पाद जोड़ें',
     ssp : 'खरीदारी शुरू करें',
     wish : 'विशलिस्ट',
     wish2 : 'अपकि विशलिस्ट खाली है !',
     wish3 : 'ऑर्डर देने के लिए उत्पादों को अपनी विशलिस्ट में जोड़ें',
     to : 'ट्रैक ऑर्डर',
     all2 : 'सभी',
     pen : 'पेंडिंग',
     del : 'पहुंचा दिया',
     can2 : 'रद्द',
     nor : 'कोई ऑर्डर नहीं मिला!',
     py : 'भुगतान',
     pym : 'भुगतान विधि',
     pym2 : 'अपनी भुगतान विधि चुनें',
     bal : 'बैलेंस',
     inst : 'किस्त',
     comp : 'पूर्ण भुगतान',
     payn : 'भुगतान करें',
     noti : 'सूचनाएं',
     noti2 : 'अभी तक कोई सूचना नहीं!',
     epr : 'प्रोफाइल में बदलाव करें ',
     ma : 'मेरा पता',
     mo : 'मेरे ऑर्डर',
     si : 'दुकान की जानकारी',
     mw : 'विशलिस्ट',
     cu : 'हमारे साथ चैट करें',
     ts : 'ग्राहक सेवा अधिकारी से बात करें ',
     pp : 'गोपनीयता नीति',
     mu : 'हमें मेल करें',
     da : 'प्रोफाइल निष्क्रिय करें',
     lg : 'लॉग आउट',
     lg2 : 'निश्चित रूप से लॉगआउट करें?',
     lg3 : 'क्या आप वाकई ग्रामिक से लॉगआउट करना चाहते हैं?',
     pd : 'उत्पाद की जानकारी',
     prc : 'कीमत',
     sz : 'आकार',
     sv : 'वैरिएंट चुनें',
     po : 'उत्पाद की सम्पूर्ण जानकारी',
     bs : 'सर्वश्रेष्ठ बिक्री',
     cr : 'ग्राहक समीक्षाएँ',
     st : 'सितारे',
     rp : 'उत्पाद की समीक्षा करें',
     rp2 : 'अन्य ग्राहकों के साथ अपने विचार साझा करें',
     wpr : 'उत्पाद की समीक्षा लिखें',
     ac : 'कार्ट में जोड़ें',
     by : 'अभी खरीदें',
     rpr : 'उत्पाद को रेट करें',
     tyr : 'अपनी समीक्षा टाइप करें...',
     smp : 'मिलते जुलते उत्पाद',
     vf : 'सत्यापित किसान',
     ph : 'लोगों को यह उपयोगी लगा',
     hp : 'मददगार?',
     sf : 'किसान चयन',
     sb : 'जमा करें',
     wl : 'स्वागत!',
     nm : 'नाम',
     em : 'ईमेल',
     phn : 'फोन नंबर',
     pin : 'पिन कोड',
     sa : 'दुकान का पता',
     vl : 'गांव / शहर',
     ds : 'ज़िला',
     opt : 'वैकल्पिक',
     upc : 'फर्म/दुकान का पैन कार्ड अपलोड करें',
     usl : 'बीज लाइसेंस अपलोड करें',
     upl : 'कीटनाशक लाइसेंस अपलोड करें',
     ufl : 'उर्वरक लाइसेंस अपलोड करें',
     usp : 'दुकान का फोटो अपलोड करें',
     eg2 : 'जीएसटी नंबर अपलोड करें',
     rmp : 'कार्ट से उत्पाद हटाएँ!',
     rmp2 : 'क्या आप इस उत्पाद को कार्ट से हटाना चाहते हैं?',
     yr : 'हाँ, हटाएँ',
     bd : 'बिल विवरण',
     sub : 'कुल योग',
     tax : 'कर',
     shp : 'शिपिंग शुल्क',
     tp : 'कुल योग',
     ptc : 'चेकआउट करें',
     cd : 'कूपन छूट',
     acc : 'कूपन कोड लागू करें',
     sc : 'कूपन चुनें',
     ca : 'कूपन लागू',
     rmv : 'हटाएँ',
     sdt : 'शिपिंग विवरण',
     cda : 'डिलिवरी पता चुनें',
     sha : 'शिपिंग पता',
     sho : 'शिपिंग की विधि',
     db : 'डिलीवरी तारीख',
     ptp : 'भुगतान करें',
     sad : 'पता चुनें',
     upa : 'पता बदलें',
     sadd : 'पता चुनें',
     edd : 'पता संपादित करें',
     add2 : 'पता जोड़ें',
     fa : 'पूरा पता',
     lnd : 'नजदीकी जगह',
     spa : 'प्राथमिक पते के रूप में सहेजें',
     dela : 'पता हटाएँ',
     dela2 : 'क्या आप वाकई इस शिपिंग पते को हटाना चाहते हैं?',
     yd : 'हाँ, हटाएँ',
     addr : 'पता',
     nad : 'कोई पता नहीं मिला!',
     nad2 : 'ऑर्डर देने के लिए पता जोड़ें',
     adn : 'अभी जोड़ें',
     payd : 'भुगतान विवरण',
     plo : 'ऑर्डर करें',
     paym : 'भुगतान विधि चुनें',
     done : 'भुगतान सफल!',
     done2 : 'आपका आर्डर सफलता पूर्वक सम्पन्न हुआ!!',
     fail : "हम आपका भुगतान आगे नहीं बढ़ा सके!",
     fail2 : 'कृपया, अपनी भुगतान विधि बदलें या पुनः प्रयास करें',
     try : 'पुनः प्रयास करें',
     ch : 'परिवर्तन',
     plo2 : 'आर्डर तारीख',
     itm : 'सामान',
     due : 'नियत दिन',
     od : 'ऑर्डर विवरण',
     por : 'उत्पादों का ऑर्डर',
     qy : 'मात्रा',
     oid : 'ऑर्डर संख्या',
     tm : 'कुल योग',
     opl : 'आर्डर तारीख',
     ocn : 'आर्डर पुष्टि',
     osp : 'ऑर्डर भेज दिया',
     ofd : 'डिलीवरी के लिए निकले हैं',
     odl : 'ऑर्डर डिलीवर किया',
     noa : 'उपलब्ध नहीं है',
     csp : 'समर्थन से संपर्क करें',
     cano : 'ऑर्डर रद्द',
     pya : 'चुकाई गई राशि',
     pna : 'बकाया राशि',
     reo : 'दोबारा आर्डर कर्रें',
     doi : 'कोटेशन/चालान डाउनलोड करें',
     rnr : 'रेटिंग एवं समीक्षा',
     rnr2 : 'अन्य ग्राहकों के साथ अपने विचार साझा करें',
     rnr3 : 'आपने इस आदेश का मूल्यांकन किया',
     tex : 'अपने अनुभव के बारे में बताएं..',
     cls : 'बंद करें',
     canr : 'कृपया रद्द करने का कारण बताएं!!',
     slr : 'कारण चुनें',
     do2 : 'क्या आप वाकई अपना ग्रामिक खाता हटाना चाहते हैं?',
     sbc : 'श्रेणी के आधार पर खोजें',
     sbb : 'ब्रांड द्वारा खोजें',
     prd : 'उत्पाद',
     sry : 'क्षमा करें, हमें आपकी खोज से कोई मेल खाता परिणाम नहीं मिला।',
     exc : 'श्रेणियाँ खोजें',
     res : 'हाल की खोज',
     cla : 'सभी हटाएं',
     exb : 'ब्रांड्स का अन्वेषण करें',
     npf : 'कोई उत्पाद नहीं मिला!',
     npf2 : 'अन्य श्रेणी या ब्रांडों में उत्पाद खोजें',
     sfl : 'फ़िल्टर चुनें',
     sfl2 : 'उत्पादों को क्रमबद्ध या फ़िल्टर करें',
     ct2 : 'श्रेणियाँ',
     brd : 'ब्रांड्स',
     clr : 'रीसेट',
     flt : 'फ़िल्टर',
     flp : 'फ़िल्टर किए गए उत्पाद',
     su : 'इकाई का चयन करें',
     add : 'जोड़ें',
     vcrt : 'कार्ट देखें',
     wyn : 'आपका नाम क्या है?',
     ename : 'नाम दर्ज करें',
     cnt : 'आगे बढ़ें',
     recv : 'हाल ही में देखा गया',
     out : '5 में से',
     things : 'जानने योग्य बातें',
     sow : 'बुआई का समय',
     har : 'कटाई',
     review : 'समीक्षा',
     area : 'बुआई का क्षेत्रफल',
     coup : 'कूपन',
     ecode : 'कोड दर्ज करें',
     acc2 : 'कोड लागू करें',
     apply : 'प्रयोग करें',
     ssa : 'शिपिंग पता चुनें',
     grw : 'ग्रामिक वॉलेट',
     hom : 'डैशबोर्ड',
     shop : 'खरीदारी',
     ord3 : 'ऑर्डर',
     acct : 'प्रोफाइल',
     afd : 'किसान विवरण जोड़ें',
     laa : 'कुल भूमि क्षेत्र ( एकड़ में )',
     csa : 'वार्षिक रूप से बोई जाने वाली फसल',
     csc : 'वर्तमान में बोई गई फसल',
     catt : 'क्या आपके पास कोई पशु है?',
     kisan : 'क्या आपके पास किसान क्रेडिट कार्ड है?',
     tractor : 'क्या आपके पास ट्रैक्टर है?',
     adhaar : 'अपना आधार कार्ड अपलोड करें',
     upan : 'अपना पैन कार्ड अपलोड करें',
     crf : 'क्या आप क्रेडिट सुविधा का लाभ उठाना चाहते हैं?',
     save : 'सेव',
     nny : 'अभी तक कोई अधिसूचना नहीं!',
     nny2 : 'ऑर्डर देने के लिए अपने कार्ट में उत्पाद जोड़ें',
     lang : 'भाषा',
     lang2 : 'अपनी भाषा का चयन करें',
     avb : 'उपलब्ध शेष राशि',
     addm : 'पैसे जोड़ें',
     ltr : 'अंतिम लेनदेन',
     notr : 'अभी तक लेन-देन नहीं!',
     wtp : 'वॉलेट टॉपअप!',
     wtp2 : 'आसान ऑर्डर भुगतान के लिए अपने वॉलेट को टॉपअप करें',
     ena : 'राशि डालें',
     topw : 'टॉपअप वॉलेट',
     hello : 'नमस्ते',
     tos : "आज की बिक्री",
     tots : 'कुल बिक्री',
     ya : 'हासिल किया',
     tmt : 'माह लक्ष्य',
     lms : 'पिछले महीने की बिक्री',
     lmt : 'पिछले माह का लक्ष्य',
     toto : 'कुल ऑर्डर',
     peno : 'पेंडिंग ऑर्डर',
     delo : 'डेलिवर्ड आर्डर',
     backl : 'बकाया',
     cru : 'क्रेडिट का उपयोग',
     yfar : 'आपके किसान',
     totf : 'कुल किसान',
     recently : 'हाल ही में',
     recently2 : 'इस माह किसानों को जोड़ा गया',
     recently3 : 'कॉर्डिनेटर को इस महीने जोड़ा गया है',
     blc : "ब्लॉक समन्वयक",
     totc : "कुल समन्वयक",
     peerp : 'सहकर्मी भागीदार',
     totp : "कुल सहकर्मी भागीदार",
     myfar : 'मेरे किसान',
     creditf : 'ऋण सुविधा',
     tcr : 'कुल क्रेडिट',
     pena : 'बकाया राशि',
     tots2 : 'कुल खर्च',
     repay : 'पुनर्भुगतान',
     stm : 'इस महीने बिताया',
     month : 'महीने के',
     week : 'साप्ताहिक',
     year : 'सालाना',
     allt : 'पूरे समय',
     spi : 'खर्चा',
     cred : 'क्रेडिट',
     selc : 'फसलें चुनें',
     selt : 'चुने हुए',
     post : 'पोस्ट ऑफ़िस',
     rmf : 'किसान हटाएं?',
     rmf2 : 'क्या आप वाकई इस किसान को हटाना चाहते हैं?',
     update : 'अपडेट उपलब्ध',
     update2 : 'कृपया सभी सुविधाओं तक पहुंचने के लिए ग्रामिक ऐप को अपडेट करें',
     updaten : 'अपडेट',
     guest : 'अतिथि के रूप में काउंटिन्यू करें',
     cmeet : 'किसान मीटिंग बनाएं',
     cmeet2 : 'किसान मीटिंग विवरण दर्ज करें',
     date : 'तारीख़ चुनें',
     fmeet : 'किसान मीटिंग',
     tdy : 'आज',
     tmr : 'कल',
     week : 'पूरे सप्ताह',
     nmeet : 'कोई मीटिंग नहीं मिली!',
     addf : 'किसान जोड़ें',
     mphoto : 'मीटिंग की तस्वीरें',
     mphoto2 : 'तस्वीरें जोड़ें',
     trt : 'उपचार से पहले तस्वीरें',
     trt2 : 'उपचार के बाद की तस्वीरें',
     ntr : 'कोई उत्पाद परीक्षण नहीं मिला!',
     ctr : 'उत्पाद परीक्षण बनाएँ',
     prt : 'उत्पाद ट्रेल्स',
     sela : 'एजेंडा चुनें',
     selm : 'मीटिंग प्रकार चुनें',
     selc2 : 'एसोसिएट सेंटर का चयन करें',
     selc3 : 'किसान फसलें चुनें',
     locd : 'स्थान विवरण',
     ens : 'राज्य दर्ज करें',
     end : 'जिला दर्ज करें',
     enb : 'ब्लॉक दर्ज करें',
     env : 'गांव दर्ज करें',
     frn : 'किसान का नाम',
     totl : 'कुल भूमि (बिसवा)',
     trtl : 'उपचारित भूमि (बिसवा)',
     dos : 'बुआई की तिथि',
     selcr : 'फसल का चयन करें',
     selpr : 'उत्पाद का चयन करें',
     bti : 'उपचार से पहले छवियाँ',
     lgn : 'ग्रामिक लॉगिन',
     lgn2 : 'सभी सुविधाओं तक पहुंचने के लिए ग्रामिक ऐप में लॉग इन करें',
     lgn3 : 'अभी लॉगिन करें',
     srt : 'रिटेलर चुनें',
     ard : 'विक्रेता विवरण जोड़ें',
     addq : 'मात्रा जोड़ें',
     nr : 'कोई खुदरा विक्रेता नहीं मिला!',
     nr2 : 'ऑर्डर देने के लिए खुदरा विक्रेताओं को जोड़ें',
     crd : 'मांग बनाएँ',
     dsn : 'जिले का नाम',
     bln : 'ब्लॉक का नाम',
     agn : 'एजेंट का नाम',
     retn : 'खुदरा विक्रेता का नाम',
     retmn : 'खुदरा विक्रेता का मोबाइल नंबर',
     comc : 'आने वाली फसल',
     brn : 'ब्रांड का नाम',
     prn : 'प्रोडक्ट का नाम',
     vrt : 'प्रकार',
     expr : 'अपेक्षित दर',
     selb : 'ब्रांड चुनें',
     qy2 : 'मात्रा (पीस)',
     upp : 'भुगतान स्थिति बदलें',
     scr : 'एनईएफटी/आरटीजीएस स्क्रीनशॉट संलग्न करें',
     tnx : 'लेनदेन आईडी (वैकल्पिक)',
     trm : 'प्रशिक्षण सामग्री',
     train : 'प्रशिक्षण',
     leaf : 'पुस्तिकाएं',
     ndoc : 'कोई दस्तावेज़ नहीं मिला!',
     doc : 'दस्तावेज़',
     mret : 'मेरे खुदरा विक्रेता',
     ref : 'ऐप रेफरल',
     eg3 : 'जीएसटी नंबर',
     usl2 : 'बीज लाइसेंस नंबर',
     upl2 : 'कीटनाशक लाइसेंस नंबर',
     ufl2 : 'उर्वरक लाइसेंस संख्या',
     qoute : 'उद्धृत दर',
     refc : 'रेफरल कोड',
     nref : 'कोई ऐप रेफ़रल नहीं मिला!',
     nref2 : 'ग्रामिक रिटेलर ऐप को रेफर करें और शेयर करें',
     nref3 : 'ऐप लिंक साझा करें',
     ats : 'स्क्रीनशॉट संलग्न करें',
     tra : 'स्थानांतरण राशि',
     tdp : 'आज की खरीदारी',
     prc2 : 'कीमत',
     sz2 : 'पैक का आकार',
     dml : 'मांग सूची',
     cnm : 'पुष्टीकृत',
     nod : 'कोई मांग नहीं मिली!',
     khata : 'खाता बुक',
     gmka : 'डॉ क्रांति',

avcoins : 'उपलब्ध कॉइन्स',
upcc : 'फसल या पशु की छवि अपलोड करें',
chs : 'स्रोत चुनें',
tlkx : 'हमारे विशेषज्ञों से बात करें',
nmf : 'अभी तक कोई इतिहास नहीं!',
nmf2 : 'डॉ क्रांति एआई यहां आपके कृषि या पशुपालन से जुड़े किसी भी समस्या में सहायता के लिए है।',
hold: '1-2 मिनट रुकिए! डॉ. क्रांति विश्लेषण कर रहे हैं...',
tyq : 'अपना प्रश्न टाइप करें...',
ingc : 'अपर्याप्त ग्रामिक सिक्के',
   grcom : 'ग्रामिक कम्युनिटी',
     like : 'लाइक',
     comments : 'कॉमेंट्स',
     upos : 'अपडेट ',
     retd : "रिटेलर का विवरण",
     seld: "डिस्ट्रिब्यूटर चुनें"




  },
//   marathi: {
//     w1 : "भारत के कृषि उत्पाद ऑनलाइन स्टोर से खरीदारी करें",
//     w2 : 'सभी उत्पादों के बीच सर्वोत्तम मात्रा तक पहुंचना अब बहुत आसान है',
//     nx : 'अगला',
//     wht : "आपका मोबाइल नंबर क्या हे?",
//     mob : 'मोबाइल नंबर',
//     mt : 'आपको शीघ्र ही एक सत्यापन कोड प्राप्त होगा',
//     sn : 'ओटीपी भेजें',
//     cn : 'अतिथि के रूप में जारी रखें',
//     sn2 : '5-अंकीय कोड दर्ज करें और भेजें',
//     rc : 'कोड प्राप्त नहीं हुआ?',
//     ro : 'ओटीपी दोबारा भेजें',
//     vo : 'सत्यापित करें',
//     sd : 'अपनी दुकान का विवरण दर्ज करें',
//     sd2 : 'कृपया अपनी दुकान का नाम, पता, जीएसटी, पैन नंबर दर्ज करें। वगैरह।',
//     sp : 'दुकान का नाम',
//     rq : 'आवश्यक',
//     ep : 'पैन नंबर दर्ज करें.',
//     eg : 'जीएसटी नंबर दर्ज करें (वैकल्पिक)',
//     um : 'एमएसएमई अपलोड करें',
//     yes : 'हाँ',
//     no : 'नहीं',
//     up : 'अपलोड',
//     agree : 'मैं उपर्युक्त घोषणा से सहमत हूं',
//     pr : 'आगे बढ़ना',
//     i : 'मैं',
//     dec : 'इसके द्वारा पुष्टि की जाती है कि वर्तमान में हम एमएसएमई अधिनियम के तहत पंजीकृत उद्यम नहीं हैं। मैं यह भी आश्वासन देता हूं कि, यदि भविष्य में, हम एमएसएमई अधिनियम के तहत पंजीकृत होंगे, तो हम आपको तुरंत सूचित करेंगे।',
//     up2 : 'अपलोड किए गए',
//     pro : 'आगे बढ़ना',
//     so : 'विकल्प चुनें',
//     cam : 'कैमरा',
//     gal : 'गैलरी',
//     can : 'रद्द करना',
//     sr : 'खोज',
//     spc : 'वर्गों के अनुसार खरीदारी',
//     top : 'सर्वाधिक बिकने वाले उत्पाद',
//     micro : 'सूक्ष्म पोषक तत्व',
//     short : 'ग्रामिक शॉर्ट्स',
//     spb : 'ब्रांड्स द्वारा खरीदारी करें',
//     kheti : 'खेती की जानकारी',
//     all : 'सभी को देखें',
//     see : 'और देखें',
//     mc : 'मेरा कार्ट',
//     ec : 'आपका कार्ट खाली है !',
//     ec2 : 'ऑर्डर देने के लिए अपने कार्ट में उत्पाद जोड़ें',
//     ssp : 'खरीदारी शुरू करें',
//     wish : 'विशलिस्ट',
//     wish2 : 'अपकि विशलिस्ट खाली है !',
//     wish3 : 'ऑर्डर देने के लिए उत्पादों को अपनी विशलिस्ट में जोड़ें',
//     to : 'ट्रैक ऑर्डर',
//     all2 : 'सभी',
//     pen : 'पेंडिंग',
//     del : 'पहुंचा दिया',
//     can2 : 'रद्द',
//     nor : 'कोई ऑर्डर नहीं मिला!',
//     py : 'भुगतान',
//     pym : 'भुगतान विधि',
//     pym2 : 'अपनी भुगतान विधि चुनें',
//     bal : 'बैलेंस',
//     inst : 'किस्त',
//     comp : 'पूर्ण भुगतान',
//     payn : 'भुगतान करें',
//     noti : 'सूचनाएं',
//     noti2 : 'अभी तक कोई सूचना नहीं!',
//     epr : 'प्रोफाइल में बदलाव करें ',
//     ma : 'मेरा पता',
//     mo : 'मेरे ऑर्डर',
//     si : 'दुकान की जानकारी',
//     mw : 'विशलिस्ट',
//     cu : 'हमारे साथ चैट करें',
//     ts : 'ग्राहक सेवा अधिकारी से बात करें ',
//     pp : 'गोपनीयता नीति',
//     mu : 'हमें मेल करें',
//     da : 'प्रोफाइल निष्क्रिय करें',
//     lg : 'लॉग आउट',
//     lg2 : 'निश्चित रूप से लॉगआउट करें?',
//     lg3 : 'क्या आप वाकई ग्रामिक से लॉगआउट करना चाहते हैं?',
//     pd : 'उत्पाद की जानकारी',
//     prc : 'कीमत',
//     sz : 'आकार',
//     sv : 'वैरिएंट चुनें',
//     po : 'उत्पाद अवलोकन',
//     bs : 'सर्वश्रेष्ठ बिक्री',
//     cr : 'ग्राहक समीक्षाएँ',
//     st : 'सितारे',
//     rp : 'उत्पाद की समीक्षा करें',
//     rp2 : 'अन्य ग्राहकों के साथ अपने विचार साझा करें',
//     wpr : 'उत्पाद की समीक्षा लिखें',
//     ac : 'कार्ट में जोड़ें',
//     by : 'अभी खरीदें',
//     rpr : 'उत्पाद को रेट करें',
//     tyr : 'अपनी समीक्षा टाइप करें...',
//     smp : 'समान उत्पाद',
//     vf : 'सत्यापित किसान',
//     ph : 'लोगों को यह उपयोगी लगा',
//     hp : 'मददगार?',
//     sf : 'किसान चयन',
//     sb : 'जमा करना',
//     wl : 'स्वागत!',
//     nm : 'नाम',
//     em : 'ईमेल',
//     phn : 'फोन नंबर',
//     pin : 'पिन कोड',
//     sa : 'दुकान का पता',
//     vl : 'गांव / शहर',
//     ds : 'ज़िला',
//     opt : 'वैकल्पिक',
//     upc : 'फर्म/दुकान का पैन कार्ड अपलोड करें',
//     usl : 'बीज लाइसेंस अपलोड करें',
//     upl : 'कीटनाशक लाइसेंस अपलोड करें',
//     ufl : 'उर्वरक लाइसेंस अपलोड करें',
//     usp : 'दुकान का फोटो अपलोड करें',
//     eg2 : 'जीएसटी नंबर अपलोड करें',
//     rmp : 'कार्ट से उत्पाद हटाएँ!',
//     rmp2 : 'क्या आप इस उत्पाद को कार्ट से हटाना चाहते हैं?',
//     yr : 'हाँ, हटाएँ',
//     bd : 'बिल विवरण',
//     sub : 'कुल योग',
//     tax : 'कर',
//     shp : 'शिपिंग शुल्क',
//     tp : 'कुल योग',
//     ptc : 'चेकआउट करें',
//     cd : 'कूपन छूट',
//     acc : 'कूपन कोड लागू करें',
//     sc : 'कूपन चुनें',
//     ca : 'कूपन लागू',
//     rmv : 'हटाना',
//     sdt : 'शिपिंग विवरण',
//     cda : 'डिलिवरी पता चुनें',
//     sha : 'शिपिंग पता',
//     sho : 'शिपिंग की विधि',
//     db : 'डिलीवरी तारीख',
//     ptp : 'भुगतान करें',
//     sad : 'पता चुनें',
//     upa : 'पता बदलें',
//     sadd : 'पता चुनें',
//     edd : 'पता संपादित करें',
//     add : 'पता जोड़ें',
//     fa : 'पूरा पता',
//     lnd : 'सीमाचिह्न',
//     spa : 'प्राथमिक पते के रूप में सहेजें',
//     dela : 'पता हटाएँ',
//     dela2 : 'क्या आप वाकई इस शिपिंग पते को हटाना चाहते हैं?',
//     yd : 'हाँ, हटाएँ',
//     addr : 'पता',
//     nad : 'कोई पता नहीं मिला!',
//     nad2 : 'ऑर्डर देने के लिए पता जोड़ें',
//     adn : 'अभी जोड़ें',
//     payd : 'भुगतान विवरण',
//     plo : 'ऑर्डर करें',
//     paym : 'भुगतान विधि चुनें',
//     done : 'भुगतान सफल!',
//     done2 : 'आपका आर्डर सफलता पूर्वक सम्पन्न हुआ!!',
//     fail : "हम आपका भुगतान आगे नहीं बढ़ा सके!",
//     fail2 : 'कृपया, अपनी भुगतान विधि बदलें या पुनः प्रयास करें',
//     try : 'पुनः प्रयास करें',
//     ch : 'परिवर्तन',
//     plo2 : 'आर्डर तारीख',
//     itm : 'सामान',
//     due : 'नियत दिन',
//     od : 'ऑर्डर विवरण',
//     por : 'उत्पादों का ऑर्डर',
//     qy : 'मात्रा',
//     oid : 'ऑर्डर संख्या',
//     tm : 'कुल योग',
//     opl : 'आर्डर तारीख',
//     ocn : 'आर्डर पुष्टि',
//     osp : 'ऑर्डर भेज दिया',
//     ofd : 'डिलीवरी के लिए निकले हैं',
//     odl : 'ऑर्डर डिलीवर किया',
//     noa : 'उपलब्ध नहीं है',
//     csp : 'समर्थन से संपर्क करें',
//     cano : 'ऑर्डर रद्द',
//     pya : 'चुकाई गई राशि',
//     pna : 'बकाया राशि',
//     reo : 'पुन: व्यवस्थित करें',
//     doi : 'चालान डाउनलोड करें',
//     rnr : 'रेटिंग एवं समीक्षा',
//     rnr2 : 'अन्य ग्राहकों के साथ अपने विचार साझा करें',
//     rnr3 : 'आपने इस आदेश का मूल्यांकन किया',
//     tex : 'अपने अनुभव के बारे में बताएं..',
//     cls : 'बंद करें',
//     canr : 'कृपया रद्द करने का कारण बताएं!!',
//     slr : 'कारण चुनें',
//     do2 : 'क्या आप वाकई अपना ग्रामिक खाता हटाना चाहते हैं?',
//     sbc : 'श्रेणी के आधार पर खोजें',
//     sbb : 'ब्रांड द्वारा खोजें',
//     prd : 'उत्पाद',
//     sry : 'क्षमा करें, हमें आपकी खोज से कोई मेल खाता परिणाम नहीं मिला।',
//     exc : 'श्रेणियाँ खोजें',
//     res : 'हाल की खोज',
//     cla : 'सभी हटाएं',
//     exb : 'ब्रांड्स का अन्वेषण करें',
//     npf : 'कोई उत्पाद नहीं मिला!',
//     npf2 : 'अन्य श्रेणी या ब्रांडों में उत्पाद खोजें',
//     sfl : 'फ़िल्टर चुनें',
//     sfl2 : 'उत्पादों को क्रमबद्ध या फ़िल्टर करें',
//     ct2 : 'श्रेणियाँ',
//     brd : 'ब्रांड्स',
//     clr : 'रीसेट',
//     flt : 'फ़िल्टर',
//     flp : 'फ़िल्टर किए गए उत्पाद',
//     su : 'इकाई का चयन करें',
//     add : 'जोड़ें',
//     vcrt : 'कार्ट देखें',
//     wyn : 'आपका नाम क्या है?'


//  }
};
export default languages;
